version: 2.1

orbs:
  heroku: circleci/heroku@1.2.2. # Invoke the Heroku orb

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          # filters:
          #   branches:
          #     only: sequential-branch-filter
jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.3-node
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
      - image: postgres:12.4-alpine
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    working_directory: ~/new_easy_ride #~/circleci-demo-workflows
    steps:
      - checkout
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      # Database setup
      - run: bundle exec rake db:create db:schema:load
      - run:
          name: Run tests
          command: rake
