version: 2.1

orbs:
  heroku: circleci/heroku@1.2.2 # Invoke the Heroku orb
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

executors:
  heroku: heroku/default

workflows:
  heroku_deploy:
    jobs:
      - build
      - deploy: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: master
jobs:
  deploy:
    executor:
      name: heroku
    steps:
      - heroku/install
      - heroku/check-authentication
      - checkout
      - heroku/deploy-via-git:
          force: true
  build:
    docker:
      - image: cimg/ruby:2.7.2-node
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference

      - image: circleci/postgres:9.5.19-alpine
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
        environment:
          POSTGRES_USER: easy_ride
          POSTGRES_DB: easy_ride_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: easy_ride
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      # Bundle install dependencies
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      # Database setup
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Run tests
          command: rake
